### ISSUE TITLE
Error in next tick when using switch in sub schemas

### ISSUE THREAD

**Issue by shirulaf** [koumoul-dev/vuetify-jsonschema-form#214]
Hi, 

There is an issue with the DOM changing while editing a sub schema, wrapped in OneOF, with a switch.

**How to reproduce:**
https://codepen.io/shirulaf/pen/GRNPMPM?editors=1010

1. Select the presented item to edit
2. Change the switch mode

**See that:**
1. In the view - the presented item data is not updated
2. The data in the model is updated
3. The next error is thrown:

`[Vue warn]: Error in nextTick: "TypeError: s.$refs[("item-" + i)] is undefined"
found in
---> <VJsf>... (1 recursive calls)
       <VForm>
         <VApp>
           <Root> vue.js:634:17`

Also, when not wrapping in oneOf, we see that the view is being updated,  although the error is still being thrown.

**Comment by albanm** [comment]
The [editable array example from the doc](https://koumoul-dev.github.io/vuetify-jsonschema-form/latest/examples#editable-array) was also broken with the same error message. I fixed it and released a patch version, can you check if your use-case is also fixed ?

**Comment by lirantiebloom** [comment]
Hi,

By using version 1.23.0, it seems the view is updated, however the `const` from the drop down appears as `[object object]` 
When using latest  / 1.23.9 the problem still persists, the view does not update, the data and the model is updated. 
Following error appears :

`Blocked autofocusing on a <input> element in a cross-origin subframe. `

**Comment by albanm** [comment]
I think this is solved in latest release.

**Comment by lirantiebloom** [comment]
Thanks, by explicitly using 1.24.1 and not latest, the issue does resolve :)
