### ISSUE TITLE
release of v3 alpha

### ISSUE THREAD

**Issue by albanm** [koumoul-dev/vuetify-jsonschema-form#420]
I just released version 3.0.0-alpha.0. Its documentation is published in the "next" subfolder [here](https://koumoul-dev.github.io/vuetify-jsonschema-form/next/). It is published on npm with the "next" tag (npm instal @koumoul/vjsf@next).

This is a very early release, there is still a ton of work to be done. But if some people are willing to test installation, run a few simple cases, provide feedback on the overall design, etc, that would be helpful.

The core is almost done I think, the remaining work is mostly in the ui components and in the [v2compat function](https://koumoul-dev.github.io/vuetify-jsonschema-form/next/2to3). I ported all the [examples from v2](https://koumoul-dev.github.io/vuetify-jsonschema-form/next/v2-compat) and the priority is now to make as many of them as possible work again.

**Comment by ocostello** [comment]
Some feedback:

* We weren't passing options in our implementation on Vue 2 so with the update and on Vue 3 I had to use the option `readOnly : false` to be able to input data to string and array fields, it doesn't look like it's the default although the docs state it is
* After the upgrade our app wouldn't build, with errors like 
```
ERROR in ./node_modules/@json-layout/core/src/state/state-node.js 2:0-95
Module not found: Error: Default condition should be last one
@ ./node_modules/@json-layout/core/src/state/index.js 5:0-69 304:27-45 330:13-27
@ ./node_modules/@json-layout/core/src/index.js 2:0-33 2:0-33
@ ./node_modules/@koumoul/vjsf/src/compat/v2.js 4:0-48 74:2-13
```
So I had to switch this 
```
      "import": {
        "default": "./src/index.js",
        "types": "./types/index.d.ts"
      }
```
to
```
      "import": {
        "types": "./types/index.d.ts",
        "default": "./src/index.js"
      }
```
in all of the package.json files for `@koumoul/vjsf` and `@json-layout`

*  I'm not sure if it's meant to still be supported but we had a schema using an array of items defined by a $ref which now works differently; as each input blurs it looks readonly and can only be edited by clicking a button

**Comment by Fosuke** [comment]
Hey, when I try using this on a vite project I am getting this error:
`Uncaught SyntaxError: The requested module '/node_modules/ajv-formats/dist/formats.js?v=67c67aed' does not provide an export named 'fullFormats' (at validate.js?v=67c67aed:1:10)`

**Comment by albanm** [comment]
I didn't have as much time as I wanted to work on vjsf these last few weeks. But still, I just released v3.0.0-alpha.1. It solves some build issues, add few missing functionalities and some improvements to the doc site. I am quite happy with the new editor (https://koumoul-dev.github.io/vuetify-jsonschema-form/next/editor), it looks like bidirectional reactivity works pretty well in this version compared to the previous one as I was hoping to achieve. This is still a work in progress and there is a ton of missing stuff.

**Comment by albanm** [comment]
Concerning the management of the commonjs dependencies I just added a section [in the getting-started](https://koumoul-dev.github.io/vuetify-jsonschema-form/next/getting-started), and an example application based on a standard Vite template [here](https://github.com/koumoul-dev/vuetify-jsonschema-form/tree/next/app-examples).

**Comment by lukas-mertens** [comment]
@albanm I was struggling with it still not working until I learned that vite actually caches the commonjs conversion stuff. Make sure to do `vite --force` after changing these settings to ignore caches. Maybe you could add this info to the docs as well, might be helpful for some people

**Comment by albanm** [comment]
Sure, thanks.
